### ISSUE TITLE
Pip install Arkouda fails, claims Chapel is not installed

### ISSUE THREAD

**Issue by buddha314** [mhmerrill/arkouda#354]
```
(env) buddha@DESKTOP-ORIFC8I:/mnt/c/Users/b/tmp$ pip install arkouda
Collecting arkouda
  Using cached https://files.pythonhosted.org/packages/8c/c6/2a250112155aa50dbdecb6717d3b5a31e30c3105e954d62e5feacbaa0b2e/arkouda-2020.2.4.tar.gz
Requirement already satisfied: numpy in ./env/lib/python3.7/site-packages (from arkouda) (1.18.2)
Requirement already satisfied: zmq in ./env/lib/python3.7/site-packages (from arkouda) (0.0.0)
Requirement already satisfied: pyzmq in ./env/lib/python3.7/site-packages (from zmq->arkouda) (19.0.0)
Building wheels for collected packages: arkouda
  Running setup.py bdist_wheel for arkouda ... error
  Complete output from command /mnt/c/Users/b/tmp/env/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-vmhplizl/arkouda/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-nnvqvw4b --python-tag cp37:
  /mnt/c/Users/b/tmp/env/lib/python3.7/site-packages/setuptools/dist.py:475: UserWarning: Normalizing '2020.02.04' to '2020.2.4'
    normalized_version,
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help

  error: invalid command 'bdist_wheel'

  ----------------------------------------
  Failed building wheel for arkouda
  Running setup.py clean for arkouda
Failed to build arkouda
Installing collected packages: arkouda
  Running setup.py install for arkouda ... error
    Complete output from command /mnt/c/Users/b/tmp/env/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-vmhplizl/arkouda/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-fegzypv9/install-record.txt --single-version-externally-managed --compile --install-headers /mnt/c/Users/b/tmp/env/include/site/python3.7/arkouda:
    /mnt/c/Users/b/tmp/env/lib/python3.7/site-packages/setuptools/dist.py:475: UserWarning: Normalizing '2020.02.04' to '2020.2.4'
      normalized_version,
    running install
    running build
    running build_py
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-vmhplizl/arkouda/setup.py", line 201, in <module>
        'Chapel': 'https://chapel-lang.org'
      File "/mnt/c/Users/b/tmp/env/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/mnt/c/Users/b/tmp/env/lib/python3.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.7/distutils/command/install.py", line 589, in run
        self.run_command('build')
      File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.7/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-vmhplizl/arkouda/installers.py", line 60, in custom_run
        raise ArkoudaBuildError("Chapel is not installed, Arkouda cannot be built")
    installers.ArkoudaBuildError: Chapel is not installed, Arkouda cannot be built

    ----------------------------------------
Command "/mnt/c/Users/b/tmp/env/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-vmhplizl/arkouda/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-fegzypv9/install-record.txt --single-version-externally-managed --compile --install-headers /mnt/c/Users/b/tmp/env/include/site/python3.7/arkouda" failed with error code 1 in /tmp/pip-install-vmhplizl/arkouda/
```

However `chpl` is in the path.  This is on Ubuntu under Windows Subsystem for Linux

**Comment by buddha314** [comment]
recent pull, no longer having this problem.  Honestly don't know what fixed it.
